spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/SpringSecurity
    username: postgres
    password: Saibee@12
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  redis:
    port: 6379
    host: 127.0.0.1
jwt:
  access-token-validity: 900000
  refresh-token-validity: 604800000